# Generated by Django 3.1.3 on 2021-01-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjID', models.CharField(max_length=200)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('SPM_activations', models.CharField(max_length=200)),
                ('FS_activations', models.CharField(max_length=200)),
                ('individual_stats', models.JSONField()),
                ('SPM_SN_file', models.JSONField()),
                ('FS_SN_file', models.JSONField()),
            ],
        ),
    ]
